name: Run iCook Crawler

on:
  schedule:
    - cron: "0 */3 * * *"   # 每 3 小時跑一次（UTC 時間）
  workflow_dispatch:        # 仍可手動觸發

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies (pip + Playwright + deps)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Save Firebase key (if present)
        shell: bash
        run: |
          if [ -n "${{ secrets.SERVICE_ACCOUNT_KEY }}" ]; then
            echo "✅ SERVICE_ACCOUNT_KEY secret found"
            echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' > serviceAccountKey.json
            echo "✅ serviceAccountKey.json 已成功寫入"
            head -n 5 serviceAccountKey.json   # 顯示前 5 行確認（安全，避免洩露全部金鑰）
          else
            echo "❌ No SERVICE_ACCOUNT_KEY secret provided"
          fi

      - name: Run crawler
        run: python scrape_icook_keywords_to_firestore.py
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Upload artifacts (JSON + logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crawler-output
          path: |
            icook_keywords_sample.json
            icook_keywords_history.json
            crawler.log
